### ISSUE TITLE
[Bug]: Error generating interop assemblies

### ISSUE THREAD

**Issue by Pietrodjaowjao** [LemonLoader/MelonLoader#12]
### All of the following criteria must be met

- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the app.
- [ ] Tried reinstalling LemonLoader.
- [ ] Tried restarting the device.

### Describe the issue.

[Latest (1).log](https://github.com/user-attachments/files/17267309/Latest.1.log)

It gives an error saying that it failed to generate interop assemblies, so the chainloader just wont run

**Comment by Pietrodjaowjao** [comment]
Btw the game im using is a test i compiled for Il2cpp Stripping test, currently the options are:

Engine Stripping: Off
Managed Stripping: Low

**Comment by TrevTV** [comment]
Looks like an issue with interop (at least, a piece of it that I haven't touched).
Are you able to upload an unpatched version of the APK you used?

**Comment by Pietrodjaowjao** [comment]
Here:
https://www.mediafire.com/file/jsnyon0ppkpik8v/StrippingTest.apk/file

**Comment by TrevTV** [comment]
Not a perfect solution, but it gets the app running. Lemon throws another error due to failed unstripping (not sure why or how), but mods still seem to load fine. This will be included in the next Lemon update, but for now you can just run the patched game once then replace the DLL in `/sdcard/MelonLoader/{package name}/MelonLoader/net8` with the one in this zip.
[Il2CppInterop.Generator.dll.zip](https://github.com/user-attachments/files/17485488/Il2CppInterop.Generator.dll.zip)

**Comment by Pietrodjaowjao** [comment]
The generator keeps getting replaced with the old one.

**Comment by TrevTV** [comment]
That shouldn't be happening unless
1. You patched the game manually instead of with the installer
2. You re-patched the APK after that DLL was compiled, so my code assumes that it's older and shouldn't be used

The easy solution would just be to decompile the patched APK and replace the DLL inside instead of replacing it externally. You can do that pretty easily with [APKToolGUI](https://github.com/AndnixSH/APKToolGUI). Or you could wait for an update but I have no idea when that'll happen
